// TIPO DE ACCION
export const LogActionType = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',

    CREATE_PRODUCT: "CREATE_PRODUCT",
    EDIT_PRODUCT: "EDIT_PRODUCT",
    REVIEW_PRODUCT: "REVIEW_PRODUCT",
    APPROVE_PRODUCT_REVIEW: "APPROVE_PRODUCT_REVIEW",
    CHECK_PRODUCT: "CHECK_PRODUCT",
    TRANSFER_PRODUCT: "TRANSFER_PRODUCT",
    MARK_PRODUCT_AS_UNUSABLE: 'MARK_PRODUCT_AS_UNUSABLE',
    REPAIR_PRODUCT: 'REPAIR_PRODUCT',
    MARK_PRODUCT_AS_LOST: "MARK_PRODUCT_AS_LOST",
    MARK_PRODUCT_AS_FOUND: "MARK_PRODUCT_AS_FOUND",
    RETIRE_PRODUCT: "RETIRE_PRODUCT",
    ENABLE_PRODUCT: "ENABLE_PRODUCT",
    DELETE_PRODUCT: "DELETE_PRODUCT",

    CREATE_DEPARTMENT: "CREATE_DEPARTMENT",
    EDIT_DEPARTMENT: "EDIT_DEPARTMENT",
    ENABLE_DEPARTMENT: "ENABLE_DEPARTMENT",
    DISABLE_DEPARTMENT: "DISABLE_DEPARTMENT",
    DELETE_DEPARTMENT: "DELETE_DEPARTMENT",

    CREATE_USER: "CREATE_USER",
    EDIT_USER: "EDIT_USER",
    ENABLE_USER: "ENABLE_USER",
    DISABLE_USER: "DISABLE_USER",
    DELETE_USER: "DELETE_USER"
} as const;

export type ActionType = typeof LogActionType[keyof typeof LogActionType];

// TIPO DE ENTIDAD
export const LogEntityType = {
    PRODUCT: 'PRODUCT',
    DEPARTMENT: 'DEPARTMENT',
    USER: 'USER',
    MOVEMENT_REPORT: 'MOVEMENT_REPORT',
    MAINTENANCE_REPORT: 'MAINTENANCE_REPORT',
    LOSS_REPORT: 'LOSS_REPORT',
    RETIREMENT_REPORT: 'RETIREMENT_REPORT',
    LOG: 'LOG'
} as const;

export type EntityType = typeof LogEntityType[keyof typeof LogEntityType];
